### PR TITLE
fix: add support for vinejs messages provider by getting otherField

### LINKED ISSUE #140: Vinejs messages provider not getting otherField
### Package version

2.2.0

### Describe the bug

Hi everyone
I'm trying to translate Vine error messages. To do this, I created a `json` file defining the possible fields and error messages, following the documentation ([](https://docs.adonisjs.com/guides/digging-deeper/i18n#translating-validation-messages)).
My situation is simple: when creating a password, I need to check that the `password` field is equal to `confirmationPassword`.
So I use the `.confirmed({ confirmationField: 'confirmationPassword' })` rule, as Vinejs normally does.
But the error message, which should be `"The fields { field } and { otherField } must be identical,"` gives me `"The fields Password and confirmationPassword must be identical."`
So `otherfield` interpolated even though it is clearly defined in the `json` in shared.field (following the docs)

Here are my code snippets

```
  export const updatePasswordValidator = vine.compile(
      vine.object({
          password: vine
              .string()
              .minLength(1)
              .maxLength(255)
              .confirmed({ confirmationField: 'passwordConfirmation' }),
      })
  )
```

```
{
    "shared": {
        "fields": {
            "password": "Password",
            "passwordConfirmation": "Confirm password"
        },
        "messages": {
            "confirmed": "The fields {{ field }} and { otherField } must be identical"
        }
    }
}
```

Do you know why?
It seems like the `otherField` does not go through the translations.

### Reproduction repo

_No response_

### PR DESCRIPTION
**Pull request by Lupiac**
### 🔗 Linked issue

Vinejs messages provider not getting otherField #140

### ❓ Type of change

- [x ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Checking if vine's meta comes with `otherField`, if so it gets its translation
An error was occurring when defining validator's rule like this `"confirmed": "The {{ field }} field and {{ otherField }} field must be the same"`
Resolves #140

### 📝 Checklist

- [x ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/vine_i18n_messages_provider.ts [hunk 1]
```diff
@@ -64,7 +64,13 @@ export class I18nMessagesProvider implements MessagesProviderContact {
         ...meta,
       })
     }
-
+    /**
+     * Checking if vine's meta comes with otherField
+     */
+    if (meta?.otherField) {
```
Comment (thetutlage) [inline src/vine_i18n_messages_provider.ts]: The check has to be moved up, next to the `fieldName` translation resolution. Also, you should wrap `meta.otherField` assignment into the conditional.

```ts
if (meta?.otherField) {
      const translatedOtherFieldName = this.#i18n.resolveIdentifier(
        `${this.#fieldsPrefix}.${meta.otherField}`
      )
      if (translatedOtherFieldName) {
        meta.otherField = this.#i18n.formatRawMessage(translatedOtherFieldName.message)
      }
    }
```

**Comment by thetutlage** [comment]
Hey, thanks for the PR :)

Can you please make the changes I have suggested and then run `npm run format` before pushing the code?
